language: ruby
cache: bundler
bundler_args: --without development
services: mongodb
rvm:
  - 2.3.3
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake test
  - bundle exec rubocop -R
addons:
    code_climate:
        repo_token: YOUR_CODECLIMATE_APP_TOKEN
