version: '3'
services:
  mongo:
    image: mongo
    expose:
      - 27017

  web:
    build: .
    volumes:
      - .:/tomatoes
    entrypoint: ./docker-entrypoint.sh 
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - DO_HOST=mongo
